org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.6+1.21.11
viafabricplus_api_version=4.4.14
cloth_config_version=21.11.153
mod_menu_version=17.0.0

mod_version=0.2.0-alpha.27
group=dev.yinghuang
archives_base_name=legacyforgebridge
