package dev.longyu.legacyforgebridge.convert.manifest;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import dev.longyu.legacyforgebridge.convert.api.ConversionContext;
import dev.longyu.legacyforgebridge.convert.api.ConversionStatus;
import dev.longyu.legacyforgebridge.convert.api.LegacyModMetadata;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class FabricMetadataWriter {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private FabricMetadataWriter() {
    }

    public static void write(ConversionContext context, ConversionStatus status, boolean installable) throws IOException {
        LegacyModMetadata metadata = context.metadata();
        LegacyModMetadata.ModEntry primary = metadata.primary();

        JsonObject root = new JsonObject();
        root.addProperty("schemaVersion", 1);
        root.addProperty("id", metadata.fabricId());
        root.addProperty("version", primary.version().isBlank() ? "0.0.0+legacy" : primary.version());
        root.addProperty("name", primary.name());
        root.addProperty(
                "description",
                "Legacy Forge 1.7.10 conversion candidate generated by LegacyForgeBridge."
        );
        root.addProperty("environment", "client");

        JsonObject depends = new JsonObject();
        depends.addProperty("fabricloader", ">=0.19.3");
        depends.addProperty("minecraft", "1.21.11");
        depends.addProperty("legacyforgebridge", "*");
        root.add("depends", depends);

        JsonObject custom = new JsonObject();
        custom.addProperty("sourceFile", metadata.sourceFileName());
        custom.addProperty("sourceSha256", context.sourceHash());
        custom.addProperty("profile", context.profileId());
        custom.addProperty("status", status.name().toLowerCase());
        custom.addProperty("installable", installable);
        custom.addProperty("manifest", "legacyforgebridge/conversion-manifest.json");

        JsonArray logicalMods = new JsonArray();
        for (LegacyModMetadata.ModEntry mod : metadata.mods()) {
            JsonObject logical = new JsonObject();
            logical.addProperty("modid", mod.modId());
            logical.addProperty("name", mod.name());
            logical.addProperty("version", mod.version());
            logical.addProperty("mcversion", mod.mcVersion());
            logicalMods.add(logical);
        }
        custom.add("logicalMods", logicalMods);
        root.add("custom", objectWithLegacyForgeBridge(custom));

        Path output = context.stagingDir().resolve("fabric.mod.json");
        Files.createDirectories(output.getParent());
        Files.writeString(output, GSON.toJson(root) + "\n", StandardCharsets.UTF_8);
    }

    private static JsonObject objectWithLegacyForgeBridge(JsonObject value) {
        JsonObject custom = new JsonObject();
        custom.add("legacyforgebridge", value);
        return custom;
    }
}
