package dev.longyu.legacyforgebridge.convert.pass;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import dev.longyu.legacyforgebridge.convert.api.ConversionContext;
import dev.longyu.legacyforgebridge.convert.api.ConversionPass;
import dev.longyu.legacyforgebridge.convert.api.SupportLevel;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/** Compiles neutral conversion semantics into classes owned and executed by the converted mod. */
public final class GeneratedSemanticCodePass implements ConversionPass {
    @Override public String id() { return "generated-semantic-mod-code"; }
    @Override public void apply(ConversionContext context) throws IOException {
        Path manifest=context.stagingDir().resolve("legacyforgebridge/converted-content.json"); JsonObject root=Files.isRegularFile(manifest)?read(manifest):new JsonObject(); String cb=GeneratedModEntrypointPass.generatedContentClass(context.metadata()),clb=GeneratedModEntrypointPass.generatedClientClass(context.metadata()); Path cp=context.stagingDir().resolve(cb.replace('.','/')+".class"),clp=context.stagingDir().resolve(clb.replace('.','/')+".class"); Files.createDirectories(cp.getParent());Files.createDirectories(clp.getParent());GenerationStats s=new GenerationStats();Files.write(cp,generateContent(cb.replace('.','/'),context.metadata().fabricId(),root,s));Files.write(clp,generateClient(clb.replace('.','/'),context.metadata().fabricId(),root,s));context.diagnostics().info("LFB-CONVERT-CODEGEN-0001",SupportLevel.ADAPTED,"Compiled neutral conversion semantics into mod-owned Java 21 bytecode: items="+s.items+", creativeTabs="+s.creativeTabs+", equipmentRenderers="+s.equipmentRenderers+".");}
    private static byte[] generateContent(String n,String modId,JsonObject root,GenerationStats s){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V21,Opcodes.ACC_PUBLIC|Opcodes.ACC_FINAL|Opcodes.ACC_SUPER,n,null,"java/lang/Object",null);privateConstructor(w);MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"initialize","()V",null,null);m.visitCode();m.visitLdcInsn(modId);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","beginMod","(Ljava/lang/String;)V",false);JsonArray items=root.getAsJsonArray("items");if(items!=null)for(JsonElement e:items){if(!e.isJsonObject())continue;JsonObject i=e.getAsJsonObject();String id=string(i,"id",null);if(id==null)continue;m.visitLdcInsn(id);m.visitLdcInsn(string(i,"kind","item"));m.visitLdcInsn(string(i,"descriptionKey","item."+id.replace(':','.')));pushInt(m,integer(i,"durability",0));m.visitLdcInsn(number(i,"attackDamage",0F));m.visitLdcInsn(number(i,"attackSpeed",0F));m.visitLdcInsn(number(i,"armor",0F));m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","registerItem","(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IFFF)V",false);s.items++;}JsonArray tabs=root.getAsJsonArray("creativeTabs");if(tabs!=null)for(JsonElement e:tabs){if(!e.isJsonObject())continue;JsonObject t=e.getAsJsonObject();String id=string(t,"id",null);JsonArray ids=t.getAsJsonArray("items");if(id==null||ids==null||ids.isEmpty())continue;m.visitLdcInsn(id);m.visitLdcInsn(string(t,"titleKey",""));m.visitLdcInsn(string(t,"title",id));m.visitLdcInsn(string(t,"icon",ids.get(0).getAsString()));emitStringArray(m,primitiveStrings(ids));m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","registerCreativeTab","(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V",false);s.creativeTabs++;}m.visitLdcInsn(modId);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","finishMod","(Ljava/lang/String;)V",false);m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}
    private static byte[] generateClient(String n,String modId,JsonObject root,GenerationStats s){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V21,Opcodes.ACC_PUBLIC|Opcodes.ACC_FINAL|Opcodes.ACC_SUPER,n,null,"java/lang/Object",null);privateConstructor(w);MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"initialize","()V",null,null);m.visitCode();JsonArray items=root.getAsJsonArray("items");if(items!=null)for(JsonElement e:items){if(!e.isJsonObject())continue;JsonObject i=e.getAsJsonObject(),r=object(i,"equipmentRender");String itemId=string(i,"id",null);if(r==null||itemId==null)continue;JsonArray parts=r.getAsJsonArray("parts");if(parts==null||parts.isEmpty())continue;List<String>models=new ArrayList<>(),sets=new ArrayList<>();for(JsonElement pe:parts){if(!pe.isJsonObject())continue;JsonObject p=pe.getAsJsonObject();String model=string(p,"model",null);if(model==null)continue;models.add(model);List<String>tx=new ArrayList<>();JsonArray ta=p.getAsJsonArray("textures");if(ta!=null)tx.addAll(primitiveStrings(ta));String one=string(p,"texture",null);if(one!=null)tx.add(0,one);sets.add(String.join("\u001f",tx));}if(models.isEmpty())continue;m.visitLdcInsn(itemId);m.visitLdcInsn(string(r,"anchor","root"));m.visitInsn(bool(r,"autoCenter",true)?Opcodes.ICONST_1:Opcodes.ICONST_0);m.visitLdcInsn(number(r,"fit",1F));m.visitInsn(bool(r,"translucent",false)?Opcodes.ICONST_1:Opcodes.ICONST_0);emitStringArray(m,models);emitStringArray(m,sets);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/render/GeneratedEquipmentSupport","register","(Ljava/lang/String;Ljava/lang/String;ZFZ[Ljava/lang/String;[Ljava/lang/String;)V",false);s.equipmentRenderers++;}m.visitLdcInsn(modId);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/render/GeneratedEquipmentSupport","finishMod","(Ljava/lang/String;)V",false);m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}
    private static void privateConstructor(ClassWriter w){MethodVisitor c=w.visitMethod(Opcodes.ACC_PRIVATE,"<init>","()V",null,null);c.visitCode();c.visitVarInsn(Opcodes.ALOAD,0);c.visitMethodInsn(Opcodes.INVOKESPECIAL,"java/lang/Object","<init>","()V",false);c.visitInsn(Opcodes.RETURN);c.visitMaxs(1,1);c.visitEnd();}
    private static void emitStringArray(MethodVisitor m,List<String>v){pushInt(m,v.size());m.visitTypeInsn(Opcodes.ANEWARRAY,"java/lang/String");for(int i=0;i<v.size();i++){m.visitInsn(Opcodes.DUP);pushInt(m,i);m.visitLdcInsn(v.get(i));m.visitInsn(Opcodes.AASTORE);}}
    private static void pushInt(MethodVisitor m,int v){if(v==-1)m.visitInsn(Opcodes.ICONST_M1);else if(v>=0&&v<=5)m.visitInsn(Opcodes.ICONST_0+v);else if(v>=Byte.MIN_VALUE&&v<=Byte.MAX_VALUE)m.visitIntInsn(Opcodes.BIPUSH,v);else if(v>=Short.MIN_VALUE&&v<=Short.MAX_VALUE)m.visitIntInsn(Opcodes.SIPUSH,v);else m.visitLdcInsn(v);}
    private static List<String>primitiveStrings(JsonArray a){List<String>r=new ArrayList<>();for(JsonElement e:a)if(e.isJsonPrimitive())r.add(e.getAsString());return r;}
    private static JsonObject read(Path p)throws IOException{try(Reader r=Files.newBufferedReader(p,StandardCharsets.UTF_8)){return JsonParser.parseReader(r).getAsJsonObject();}}
    private static JsonObject object(JsonObject p,String k){JsonElement v=p.get(k);return v!=null&&v.isJsonObject()?v.getAsJsonObject():null;}
    private static String string(JsonObject o,String k,String f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsString():f;}
    private static int integer(JsonObject o,String k,int f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsInt():f;}
    private static float number(JsonObject o,String k,float f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsFloat():f;}
    private static boolean bool(JsonObject o,String k,boolean f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsBoolean():f;}
    private static final class GenerationStats{int items;int creativeTabs;int equipmentRenderers;}
}
