package dev.longyu.legacyforgebridge.convert.pass;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import dev.longyu.legacyforgebridge.convert.api.ConversionContext;
import dev.longyu.legacyforgebridge.convert.api.ConversionPass;
import dev.longyu.legacyforgebridge.convert.api.SupportLevel;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/** Compiles neutral conversion semantics into classes owned and executed by the converted mod. */
public final class GeneratedSemanticCodePass implements ConversionPass {
    @Override public String id(){return "generated-semantic-mod-code";}
    @Override public void apply(ConversionContext c)throws IOException{Path p=c.stagingDir().resolve("legacyforgebridge/converted-content.json");JsonObject r=Files.isRegularFile(p)?read(p):new JsonObject();String a=GeneratedModEntrypointPass.generatedContentClass(c.metadata()),b=GeneratedModEntrypointPass.generatedClientClass(c.metadata());Path ap=c.stagingDir().resolve(a.replace('.','/')+".class"),bp=c.stagingDir().resolve(b.replace('.','/')+".class");Files.createDirectories(ap.getParent());Files.createDirectories(bp.getParent());Stats s=new Stats();Files.write(ap,content(a.replace('.','/'),c.metadata().fabricId(),r,s));Files.write(bp,client(b.replace('.','/'),c.metadata().fabricId(),r,s));c.diagnostics().info("LFB-CONVERT-CODEGEN-0001",SupportLevel.ADAPTED,"Compiled neutral conversion semantics into mod-owned Java 21 bytecode: items="+s.items+", creativeTabs="+s.tabs+", equipmentRenderers="+s.renderers+".");}
    private static byte[] content(String n,String mod,JsonObject r,Stats s){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V21,Opcodes.ACC_PUBLIC|Opcodes.ACC_FINAL|Opcodes.ACC_SUPER,n,null,"java/lang/Object",null);ctor(w);MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"initialize","()V",null,null);m.visitCode();m.visitLdcInsn(mod);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","beginMod","(Ljava/lang/String;)V",false);JsonArray is=r.getAsJsonArray("items");if(is!=null)for(JsonElement e:is){if(!e.isJsonObject())continue;JsonObject i=e.getAsJsonObject();String id=str(i,"id",null);if(id==null)continue;m.visitLdcInsn(id);m.visitLdcInsn(str(i,"kind","item"));m.visitLdcInsn(str(i,"descriptionKey","item."+id.replace(':','.')));pi(m,integer(i,"durability",0));m.visitLdcInsn(num(i,"attackDamage",0F));m.visitLdcInsn(num(i,"attackSpeed",0F));m.visitLdcInsn(num(i,"armor",0F));m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","registerItem","(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IFFF)V",false);s.items++;}JsonArray ts=r.getAsJsonArray("creativeTabs");if(ts!=null)for(JsonElement e:ts){if(!e.isJsonObject())continue;JsonObject t=e.getAsJsonObject();String id=str(t,"id",null);JsonArray ids=t.getAsJsonArray("items");if(id==null||ids==null||ids.isEmpty())continue;m.visitLdcInsn(id);m.visitLdcInsn(str(t,"titleKey",""));m.visitLdcInsn(str(t,"title",id));m.visitLdcInsn(str(t,"icon",ids.get(0).getAsString()));arr(m,strings(ids));m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","registerCreativeTab","(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V",false);s.tabs++;}m.visitLdcInsn(mod);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/convert/runtime/GeneratedModSupport","finishMod","(Ljava/lang/String;)V",false);m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}
    private static byte[] client(String n,String mod,JsonObject r,Stats s){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V21,Opcodes.ACC_PUBLIC|Opcodes.ACC_FINAL|Opcodes.ACC_SUPER,n,null,"java/lang/Object",null);ctor(w);MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"initialize","()V",null,null);m.visitCode();JsonArray is=r.getAsJsonArray("items");if(is!=null)for(JsonElement e:is){if(!e.isJsonObject())continue;JsonObject i=e.getAsJsonObject(),q=obj(i,"equipmentRender");String id=str(i,"id",null);if(q==null||id==null)continue;JsonArray ps=q.getAsJsonArray("parts");if(ps==null||ps.isEmpty())continue;List<String>ms=new ArrayList<>(),txs=new ArrayList<>();for(JsonElement pe:ps){if(!pe.isJsonObject())continue;JsonObject x=pe.getAsJsonObject();String model=str(x,"model",null);if(model==null)continue;ms.add(model);List<String>tx=new ArrayList<>();JsonArray ta=x.getAsJsonArray("textures");if(ta!=null)tx.addAll(strings(ta));String one=str(x,"texture",null);if(one!=null)tx.add(0,one);txs.add(String.join("\u001f",tx));}if(ms.isEmpty())continue;m.visitLdcInsn(id);m.visitLdcInsn(str(q,"anchor","root"));m.visitInsn(bool(q,"autoCenter",true)?Opcodes.ICONST_1:Opcodes.ICONST_0);m.visitLdcInsn(num(q,"fit",1F));m.visitInsn(bool(q,"translucent",false)?Opcodes.ICONST_1:Opcodes.ICONST_0);arr(m,ms);arr(m,txs);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/render/GeneratedEquipmentSupport","register","(Ljava/lang/String;Ljava/lang/String;ZFZ[Ljava/lang/String;[Ljava/lang/String;)V",false);s.renderers++;}m.visitLdcInsn(mod);m.visitMethodInsn(Opcodes.INVOKESTATIC,"dev/longyu/legacyforgebridge/render/GeneratedEquipmentSupport","finishMod","(Ljava/lang/String;)V",false);m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}
    private static void ctor(ClassWriter w){MethodVisitor c=w.visitMethod(Opcodes.ACC_PRIVATE,"<init>","()V",null,null);c.visitCode();c.visitVarInsn(Opcodes.ALOAD,0);c.visitMethodInsn(Opcodes.INVOKESPECIAL,"java/lang/Object","<init>","()V",false);c.visitInsn(Opcodes.RETURN);c.visitMaxs(1,1);c.visitEnd();}
    private static void arr(MethodVisitor m,List<String>v){pi(m,v.size());m.visitTypeInsn(Opcodes.ANEWARRAY,"java/lang/String");for(int i=0;i<v.size();i++){m.visitInsn(Opcodes.DUP);pi(m,i);m.visitLdcInsn(v.get(i));m.visitInsn(Opcodes.AASTORE);}}
    private static void pi(MethodVisitor m,int v){if(v==-1)m.visitInsn(Opcodes.ICONST_M1);else if(v>=0&&v<=5)m.visitInsn(Opcodes.ICONST_0+v);else if(v>=Byte.MIN_VALUE&&v<=Byte.MAX_VALUE)m.visitIntInsn(Opcodes.BIPUSH,v);else if(v>=Short.MIN_VALUE&&v<=Short.MAX_VALUE)m.visitIntInsn(Opcodes.SIPUSH,v);else m.visitLdcInsn(v);}
    private static List<String>strings(JsonArray a){List<String>r=new ArrayList<>();for(JsonElement e:a)if(e.isJsonPrimitive())r.add(e.getAsString());return r;}
    private static JsonObject read(Path p)throws IOException{try(Reader r=Files.newBufferedReader(p,StandardCharsets.UTF_8)){return JsonParser.parseReader(r).getAsJsonObject();}}
    private static JsonObject obj(JsonObject p,String k){JsonElement v=p.get(k);return v!=null&&v.isJsonObject()?v.getAsJsonObject():null;}
    private static String str(JsonObject o,String k,String f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsString():f;}
    private static int integer(JsonObject o,String k,int f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsInt():f;}
    private static float num(JsonObject o,String k,float f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsFloat():f;}
    private static boolean bool(JsonObject o,String k,boolean f){JsonElement v=o.get(k);return v!=null&&v.isJsonPrimitive()?v.getAsBoolean():f;}
    private static final class Stats{int items;int tabs;int renderers;}
}
