package dev.yinghuang.legacyforgebridge.convert;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;

import static org.junit.jupiter.api.Assertions.*;

class LegacySeatBedPresentationAnalyzerTest {
    @TempDir Path tempDir;

    @Test void unrelatedTwoTextureFourPartTesrIsProvenWithoutModSpecificNames() throws Exception {
        Path jar=tempDir.resolve("ForeignSeat.jar");try(JarOutputStream out=new JarOutputStream(Files.newOutputStream(jar))){
            put(out,"other/seat/Tile.class",tile());put(out,"other/seat/Model.class",model());put(out,"other/seat/Renderer.class",renderer());put(out,"other/seat/Client.class",client());
            put(out,"assets/foreign/textures/entitys/seat.png",png());put(out,"assets/foreign/textures/entitys/pillow.png",png());
        }
        var source=new LegacySeatBedAnalyzer.Rule("seat_block","foreign","other/seat/Block","other/seat/Item","seat_item","other/seat/Tile","tile","other/seat/Seat$1","other/seat/Seat","Seat",.25F,true,true,true,true,true,true,true);
        var analysis=new LegacySeatBedPresentationAnalyzer().analyze(jar,source);assertTrue(analysis.diagnostics().isEmpty(),analysis.diagnostics().toString());var p=analysis.presentation().orElseThrow();
        assertEquals("other/seat/Renderer",p.sourceRendererClass());assertEquals("other/seat/Model",p.sourceModelClass());assertEquals("foreign:textures/entitys/seat.png",p.footTexture());assertEquals("foreign:textures/entitys/pillow.png",p.headTexture());
        assertEquals(java.util.List.of("p1","p2"),p.footParts());assertEquals(java.util.List.of("p0","p3"),p.headParts());assertEquals(java.util.List.of(90F,0F,270F,180F),p.yawDegreesByDirection());assertTrue(p.expandedRenderBoundsProven());
    }

    private static byte[] client(){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V1_7,Opcodes.ACC_PUBLIC,"other/seat/Client",null,"java/lang/Object",null);MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC,"register","()V",null,null);m.visitCode();m.visitLdcInsn(Type.getObjectType("other/seat/Tile"));m.visitLdcInsn("Foreign seat");m.visitTypeInsn(Opcodes.NEW,"other/seat/Renderer");m.visitInsn(Opcodes.DUP);m.visitMethodInsn(Opcodes.INVOKESPECIAL,"other/seat/Renderer","<init>","()V",false);m.visitMethodInsn(Opcodes.INVOKESTATIC,"cpw/mods/fml/client/registry/ClientRegistry","registerTileEntity","(Ljava/lang/Class;Ljava/lang/String;Lnet/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer;)V",false);m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}
    private static byte[] tile(){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V1_7,Opcodes.ACC_PUBLIC,"other/seat/Tile",null,"net/minecraft/tileentity/TileEntity",null);w.visitField(Opcodes.ACC_PUBLIC,"x","I",null,null).visitEnd();w.visitField(Opcodes.ACC_PUBLIC,"y","I",null,null).visitEnd();w.visitField(Opcodes.ACC_PUBLIC,"z","I",null,null).visitEnd();ctor(w,"net/minecraft/tileentity/TileEntity");MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC,"getRenderBoundingBox","()Lnet/minecraft/util/AxisAlignedBB;",null,null);m.visitCode();m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,"other/seat/Tile","x","I");m.visitInsn(Opcodes.ICONST_1);m.visitInsn(Opcodes.ISUB);m.visitInsn(Opcodes.I2D);m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,"other/seat/Tile","y","I");m.visitInsn(Opcodes.I2D);m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,"other/seat/Tile","z","I");m.visitInsn(Opcodes.ICONST_1);m.visitInsn(Opcodes.ISUB);m.visitInsn(Opcodes.I2D);m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,"other/seat/Tile","x","I");m.visitInsn(Opcodes.ICONST_2);m.visitInsn(Opcodes.IADD);m.visitInsn(Opcodes.I2D);m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,"other/seat/Tile","y","I");m.visitInsn(Opcodes.I2F);m.visitLdcInsn(.25F);m.visitInsn(Opcodes.FADD);m.visitInsn(Opcodes.F2D);m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,"other/seat/Tile","z","I");m.visitInsn(Opcodes.ICONST_2);m.visitInsn(Opcodes.IADD);m.visitInsn(Opcodes.I2D);m.visitMethodInsn(Opcodes.INVOKESTATIC,"net/minecraft/util/AxisAlignedBB","func_72330_a","(DDDDDD)Lnet/minecraft/util/AxisAlignedBB;",false);m.visitInsn(Opcodes.ARETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}
    private static byte[] renderer(){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);String o="other/seat/Renderer";w.visit(Opcodes.V1_7,Opcodes.ACC_PUBLIC,o,null,"net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer",null);w.visitField(Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC,"OFF","[[F",null,null).visitEnd();w.visitField(Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC,"FOOT","Lnet/minecraft/util/ResourceLocation;",null,null).visitEnd();w.visitField(Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC,"HEAD","Lnet/minecraft/util/ResourceLocation;",null,null).visitEnd();w.visitField(Opcodes.ACC_PRIVATE|Opcodes.ACC_FINAL,"model","Lother/seat/Model;",null,null).visitEnd();
        MethodVisitor c=w.visitMethod(Opcodes.ACC_PUBLIC,"<init>","()V",null,null);c.visitCode();c.visitVarInsn(Opcodes.ALOAD,0);c.visitMethodInsn(Opcodes.INVOKESPECIAL,"net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer","<init>","()V",false);c.visitVarInsn(Opcodes.ALOAD,0);c.visitTypeInsn(Opcodes.NEW,"other/seat/Model");c.visitInsn(Opcodes.DUP);c.visitMethodInsn(Opcodes.INVOKESPECIAL,"other/seat/Model","<init>","()V",false);c.visitFieldInsn(Opcodes.PUTFIELD,o,"model","Lother/seat/Model;");c.visitInsn(Opcodes.RETURN);c.visitMaxs(0,0);c.visitEnd();
        MethodVisitor main=w.visitMethod(Opcodes.ACC_PUBLIC,"func_147500_a","(Lnet/minecraft/tileentity/TileEntity;DDDF)V",null,null);main.visitCode();invokeHelper(main,o,1);invokeHelper(main,o,0);main.visitInsn(Opcodes.RETURN);main.visitMaxs(0,0);main.visitEnd();
        MethodVisitor h=w.visitMethod(Opcodes.ACC_PUBLIC,"renderPart","(Lnet/minecraft/tileentity/TileEntity;DDDFZ)V",null,null);h.visitCode();h.visitMethodInsn(Opcodes.INVOKESTATIC,"org/lwjgl/opengl/GL11","glPushMatrix","()V",false);h.visitVarInsn(Opcodes.ALOAD,1);h.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/tileentity/TileEntity","func_145832_p","()I",false);h.visitVarInsn(Opcodes.ISTORE,10);Label d=new Label(),l0=new Label(),l1=new Label(),l2=new Label(),l3=new Label();h.visitVarInsn(Opcodes.ILOAD,10);h.visitTableSwitchInsn(0,3,d,l0,l1,l2,l3);map(h,l0,1,d);map(h,l1,0,d);map(h,l2,3,d);map(h,l3,2,d);h.visitLabel(d);h.visitVarInsn(Opcodes.DLOAD,2);h.visitInsn(Opcodes.D2F);h.visitFieldInsn(Opcodes.GETSTATIC,o,"OFF","[[F");h.visitVarInsn(Opcodes.ILOAD,10);h.visitInsn(Opcodes.AALOAD);h.visitInsn(Opcodes.ICONST_0);h.visitInsn(Opcodes.FALOAD);h.visitInsn(Opcodes.FADD);h.visitVarInsn(Opcodes.DLOAD,4);h.visitInsn(Opcodes.D2F);h.visitVarInsn(Opcodes.DLOAD,6);h.visitInsn(Opcodes.D2F);h.visitFieldInsn(Opcodes.GETSTATIC,o,"OFF","[[F");h.visitVarInsn(Opcodes.ILOAD,10);h.visitInsn(Opcodes.AALOAD);h.visitInsn(Opcodes.ICONST_1);h.visitInsn(Opcodes.FALOAD);h.visitInsn(Opcodes.FADD);h.visitMethodInsn(Opcodes.INVOKESTATIC,"org/lwjgl/opengl/GL11","glTranslatef","(FFF)V",false);h.visitVarInsn(Opcodes.ILOAD,10);h.visitInsn(Opcodes.I2F);h.visitLdcInsn(90F);h.visitInsn(Opcodes.FMUL);h.visitInsn(Opcodes.FCONST_0);h.visitInsn(Opcodes.FCONST_1);h.visitInsn(Opcodes.FCONST_0);h.visitMethodInsn(Opcodes.INVOKESTATIC,"org/lwjgl/opengl/GL11","glRotatef","(FFFF)V",false);h.visitVarInsn(Opcodes.ILOAD,9);Label no=new Label();h.visitJumpInsn(Opcodes.IFEQ,no);bind(h,o);h.visitVarInsn(Opcodes.ALOAD,0);h.visitFieldInsn(Opcodes.GETFIELD,o,"model","Lother/seat/Model;");h.visitLdcInsn(.0625F);h.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"other/seat/Model","foot","(F)V",false);Label end=new Label();h.visitJumpInsn(Opcodes.GOTO,end);h.visitLabel(no);bind(h,o);h.visitVarInsn(Opcodes.ALOAD,0);h.visitFieldInsn(Opcodes.GETFIELD,o,"model","Lother/seat/Model;");h.visitLdcInsn(.0625F);h.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"other/seat/Model","head","(F)V",false);h.visitLabel(end);h.visitMethodInsn(Opcodes.INVOKESTATIC,"org/lwjgl/opengl/GL11","glPopMatrix","()V",false);h.visitInsn(Opcodes.RETURN);h.visitMaxs(0,0);h.visitEnd();
        MethodVisitor b=w.visitMethod(Opcodes.ACC_PROTECTED,"bind","(Z)V",null,null);b.visitCode();b.visitVarInsn(Opcodes.ILOAD,1);Label bf=new Label();b.visitJumpInsn(Opcodes.IFEQ,bf);b.visitVarInsn(Opcodes.ALOAD,0);b.visitFieldInsn(Opcodes.GETSTATIC,o,"FOOT","Lnet/minecraft/util/ResourceLocation;");b.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer","func_147499_a","(Lnet/minecraft/util/ResourceLocation;)V",false);Label be=new Label();b.visitJumpInsn(Opcodes.GOTO,be);b.visitLabel(bf);b.visitVarInsn(Opcodes.ALOAD,0);b.visitFieldInsn(Opcodes.GETSTATIC,o,"HEAD","Lnet/minecraft/util/ResourceLocation;");b.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer","func_147499_a","(Lnet/minecraft/util/ResourceLocation;)V",false);b.visitLabel(be);b.visitInsn(Opcodes.RETURN);b.visitMaxs(0,0);b.visitEnd();
        MethodVisitor s=w.visitMethod(Opcodes.ACC_STATIC,"<clinit>","()V",null,null);s.visitCode();s.visitInsn(Opcodes.ICONST_4);s.visitTypeInsn(Opcodes.ANEWARRAY,"[F");float[][] off={{0,.5F},{.5F,1},{1,.5F},{.5F,0}};for(int i=0;i<4;i++){s.visitInsn(Opcodes.DUP);iconst(s,i);s.visitInsn(Opcodes.ICONST_2);s.visitIntInsn(Opcodes.NEWARRAY,Opcodes.T_FLOAT);s.visitInsn(Opcodes.DUP);s.visitInsn(Opcodes.ICONST_0);fconst(s,off[i][0]);s.visitInsn(Opcodes.FASTORE);s.visitInsn(Opcodes.DUP);s.visitInsn(Opcodes.ICONST_1);fconst(s,off[i][1]);s.visitInsn(Opcodes.FASTORE);s.visitInsn(Opcodes.AASTORE);}s.visitFieldInsn(Opcodes.PUTSTATIC,o,"OFF","[[F");resource(s,o,"FOOT","foreign:textures/entitys/seat.png");resource(s,o,"HEAD","foreign:textures/entitys/pillow.png");s.visitInsn(Opcodes.RETURN);s.visitMaxs(0,0);s.visitEnd();w.visitEnd();return w.toByteArray();}
    private static byte[] model(){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);String o="other/seat/Model";w.visit(Opcodes.V1_7,Opcodes.ACC_PUBLIC,o,null,"net/minecraft/client/model/ModelBase",null);for(int i=0;i<4;i++)w.visitField(Opcodes.ACC_PUBLIC,"p"+i,"Lnet/minecraft/client/model/ModelRenderer;",null,null).visitEnd();MethodVisitor c=w.visitMethod(Opcodes.ACC_PUBLIC,"<init>","()V",null,null);c.visitCode();c.visitVarInsn(Opcodes.ALOAD,0);c.visitMethodInsn(Opcodes.INVOKESPECIAL,"net/minecraft/client/model/ModelBase","<init>","()V",false);part(c,o,"p0",0,0,-16,0,-8,8,2,16,0,0,0,0);part(c,o,"p1",0,0,-12,-2,-8,12,4,16,4,2,0,(float)Math.PI);part(c,o,"p2",0,0,-12,-2,-8,12,4,16,4,2,0,0);part(c,o,"p3",0,19,-14,2,-5,6,3,10,0,0,0,0);c.visitInsn(Opcodes.RETURN);c.visitMaxs(0,0);c.visitEnd();render(w,o,"foot","p1","p2");render(w,o,"head","p0","p3");w.visitEnd();return w.toByteArray();}
    private static void invokeHelper(MethodVisitor m,String o,int z){m.visitVarInsn(Opcodes.ALOAD,0);m.visitVarInsn(Opcodes.ALOAD,1);m.visitVarInsn(Opcodes.DLOAD,2);m.visitVarInsn(Opcodes.DLOAD,4);m.visitVarInsn(Opcodes.DLOAD,6);m.visitVarInsn(Opcodes.FLOAD,8);iconst(m,z);m.visitMethodInsn(Opcodes.INVOKEVIRTUAL,o,"renderPart","(Lnet/minecraft/tileentity/TileEntity;DDDFZ)V",false);}
    private static void map(MethodVisitor m,Label l,int v,Label d){m.visitLabel(l);iconst(m,v);m.visitVarInsn(Opcodes.ISTORE,10);m.visitJumpInsn(Opcodes.GOTO,d);}
    private static void bind(MethodVisitor m,String o){m.visitVarInsn(Opcodes.ALOAD,0);m.visitVarInsn(Opcodes.ILOAD,9);m.visitMethodInsn(Opcodes.INVOKEVIRTUAL,o,"bind","(Z)V",false);}
    private static void resource(MethodVisitor m,String o,String f,String s){m.visitTypeInsn(Opcodes.NEW,"net/minecraft/util/ResourceLocation");m.visitInsn(Opcodes.DUP);m.visitLdcInsn(s);m.visitMethodInsn(Opcodes.INVOKESPECIAL,"net/minecraft/util/ResourceLocation","<init>","(Ljava/lang/String;)V",false);m.visitFieldInsn(Opcodes.PUTSTATIC,o,f,"Lnet/minecraft/util/ResourceLocation;");}
    private static void part(MethodVisitor m,String o,String f,int u,int v,float x,float y,float z,int wi,int he,int de,float px,float py,float pz,float ry){m.visitVarInsn(Opcodes.ALOAD,0);m.visitTypeInsn(Opcodes.NEW,"net/minecraft/client/model/ModelRenderer");m.visitInsn(Opcodes.DUP);m.visitVarInsn(Opcodes.ALOAD,0);iconst(m,u);iconst(m,v);m.visitMethodInsn(Opcodes.INVOKESPECIAL,"net/minecraft/client/model/ModelRenderer","<init>","(Lnet/minecraft/client/model/ModelBase;II)V",false);m.visitFieldInsn(Opcodes.PUTFIELD,o,f,"Lnet/minecraft/client/model/ModelRenderer;");m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,o,f,"Lnet/minecraft/client/model/ModelRenderer;");fconst(m,x);fconst(m,y);fconst(m,z);iconst(m,wi);iconst(m,he);iconst(m,de);m.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/client/model/ModelRenderer","func_78789_a","(FFFIII)Lnet/minecraft/client/model/ModelRenderer;",false);m.visitInsn(Opcodes.POP);if(px!=0||py!=0||pz!=0){m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,o,f,"Lnet/minecraft/client/model/ModelRenderer;");fconst(m,px);fconst(m,py);fconst(m,pz);m.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/client/model/ModelRenderer","func_78793_a","(FFF)V",false);}if(ry!=0){m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,o,f,"Lnet/minecraft/client/model/ModelRenderer;");fconst(m,ry);m.visitFieldInsn(Opcodes.PUTFIELD,"net/minecraft/client/model/ModelRenderer","field_78796_g","F");}}
    private static void render(ClassWriter w,String o,String n,String a,String b){MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC,n,"(F)V",null,null);m.visitCode();for(String f:new String[]{a,b}){m.visitVarInsn(Opcodes.ALOAD,0);m.visitFieldInsn(Opcodes.GETFIELD,o,f,"Lnet/minecraft/client/model/ModelRenderer;");m.visitVarInsn(Opcodes.FLOAD,1);m.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/client/model/ModelRenderer","func_78785_a","(F)V",false);}m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();}
    private static void ctor(ClassWriter w,String parent){MethodVisitor m=w.visitMethod(Opcodes.ACC_PUBLIC,"<init>","()V",null,null);m.visitCode();m.visitVarInsn(Opcodes.ALOAD,0);m.visitMethodInsn(Opcodes.INVOKESPECIAL,parent,"<init>","()V",false);m.visitInsn(Opcodes.RETURN);m.visitMaxs(0,0);m.visitEnd();}
    private static void iconst(MethodVisitor m,int v){if(v>=0&&v<=5)m.visitInsn(Opcodes.ICONST_0+v);else m.visitIntInsn(Opcodes.BIPUSH,v);}private static void fconst(MethodVisitor m,float v){if(v==0)m.visitInsn(Opcodes.FCONST_0);else if(v==1)m.visitInsn(Opcodes.FCONST_1);else if(v==2)m.visitInsn(Opcodes.FCONST_2);else m.visitLdcInsn(v);}
    private static byte[] png()throws Exception{BufferedImage image=new BufferedImage(64,32,BufferedImage.TYPE_INT_ARGB);ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(image,"png",out);return out.toByteArray();}
    private static void put(JarOutputStream out,String name,byte[] bytes)throws Exception{out.putNextEntry(new JarEntry(name));out.write(bytes);out.closeEntry();}
}
