package dev.yinghuang.legacyforgebridge.convert;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.jar.*;
import javax.tools.ToolProvider;

/** Public-source semantic shapes, not a substitute for the checksum-pinned Bamboo corpus.
 * Only unrelated fixture namespace classes go into the analyzed JAR; API stubs are compile-only. */
final class LegacyAssemblySourceFixture {
    static Path create(Path root,boolean floatYaw,boolean withTextures)throws Exception{
        Map<String,String> sources=new LinkedHashMap<>();
        sources.put("net/minecraft/world/World.java","package net.minecraft.world;\npublic class World { public boolean isRemote; }");
        sources.put("net/minecraft/util/AxisAlignedBB.java","package net.minecraft.util;\npublic class AxisAlignedBB { public AxisAlignedBB setBounds(double a,double b,double c,double d,double e,double f){return this;} }");
        sources.put("net/minecraft/util/DamageSource.java","package net.minecraft.util;\npublic class DamageSource { public String getDamageType(){return \"\";} }");
        sources.put("net/minecraft/util/ResourceLocation.java","package net.minecraft.util;\npublic class ResourceLocation { public ResourceLocation(String s){} }");
        sources.put("net/minecraft/item/Item.java","package net.minecraft.item;\npublic class Item {}");
        sources.put("net/minecraft/item/ItemStack.java","package net.minecraft.item;\npublic class ItemStack { public ItemStack(Item item,int size,int meta){} }");
        sources.put("net/minecraft/entity/DataWatcher.java","package net.minecraft.entity;\npublic class DataWatcher {\n public void addObject(int i,Object value){} public void updateObject(int i,Object value){}\n public byte getWatchableObjectByte(int i){return 0;}\n public net.minecraft.item.ItemStack getWatchableObjectItemStack(int i){return null;}\n}");
        sources.put("net/minecraft/entity/Entity.java","package net.minecraft.entity;\npublic class Entity {\n public DataWatcher dataWatcher; public boolean isDead,inWater;\n public java.util.Random rand;public float rotationYaw,rotationPitch;\n public net.minecraft.util.AxisAlignedBB boundingBox;\n public Entity(net.minecraft.world.World world){} public void onUpdate(){} public void setSize(float w,float h){}\n public void setDead(){} protected void entityInit(){}\n}");
        sources.put("net/minecraft/client/model/ModelBase.java","package net.minecraft.client.model;\npublic class ModelBase { public int textureWidth=64,textureHeight=32;\n public void render(net.minecraft.entity.Entity e,float a,float b,float c,float d,float f,float scale){} }");
        sources.put("net/minecraft/client/model/ModelRenderer.java","package net.minecraft.client.model;\npublic class ModelRenderer {\n public float rotateAngleX,rotateAngleY,rotateAngleZ;public boolean mirror;\n public ModelRenderer(ModelBase m,int u,int v){}\n public ModelRenderer addBox(float x,float y,float z,int w,int h,int d){return this;}\n public void setRotationPoint(float x,float y,float z){} public ModelRenderer setTextureSize(int w,int h){return this;}\n public void render(float scale){}\n}");
        sources.put("net/minecraft/client/renderer/entity/Render.java","package net.minecraft.client.renderer.entity;\npublic class Render {\n public void bindEntityTexture(net.minecraft.entity.Entity e){}\n}");
        sources.put("org/lwjgl/opengl/GL11.java","package org.lwjgl.opengl;\npublic class GL11 {public static void glPushMatrix(){} public static void glPopMatrix(){}\n public static void glTranslatef(float x,float y,float z){} public static void glScalef(float x,float y,float z){}\n public static void glRotatef(float a,float x,float y,float z){}\n}");
        sources.put("cpw/mods/fml/common/registry/EntityRegistry.java","package cpw.mods.fml.common.registry;\npublic class EntityRegistry {\n public static void registerModEntity(Class<?> c,String name,int id,Object mod,int range,int interval,boolean velocity){}\n}");
        sources.put("cpw/mods/fml/client/registry/RenderingRegistry.java","package cpw.mods.fml.client.registry;\npublic class RenderingRegistry {\n public static void registerEntityRenderingHandler(Class<?> c,net.minecraft.client.renderer.entity.Render renderer){}\n}");
        sources.put("fixture/rotors/Base.java","package fixture.rotors;\npublic class Base extends net.minecraft.entity.Entity {\n private static int DIRECTION=16;protected float angle;\n public Base(net.minecraft.world.World w){super(w);}\n public byte heading(){return dataWatcher!=null?dataWatcher.getWatchableObjectByte(DIRECTION):0;}\n public float rotation(){return angle;}\n protected void entityInit(){angle=rand.nextInt(360);dataWatcher.addObject(DIRECTION,(byte)0);}\n public boolean canBeCollidedWith(){return !isDead;}\n public boolean attackEntityFrom(net.minecraft.util.DamageSource s,float amount){if(s.getDamageType()==\"player\")setDead();return false;}\n}");
        sources.put("fixture/rotors/Rotor.java","package fixture.rotors;\npublic class Rotor extends Base {\n public Rotor(net.minecraft.world.World w){super(w);}\n public byte size(){return dataWatcher!=null?dataWatcher.getWatchableObjectByte(19):1;}\n public void adjust(boolean smaller){\n  if(smaller){if(dataWatcher.getWatchableObjectByte(19)>1)dataWatcher.updateObject(19,(byte)(dataWatcher.getWatchableObjectByte(19)-1));}\n  else {if(dataWatcher.getWatchableObjectByte(19)<5)dataWatcher.updateObject(19,(byte)(dataWatcher.getWatchableObjectByte(19)+1));}\n }\n public void setBounds(double x,double y,double z){\n  if(heading()==0||heading()==2)boundingBox.setBounds(x-1.5*size(),y-1.5*size(),z,x+2.5*size(),y+2*size(),z+.5*size());\n  else boundingBox.setBounds(x,y-1.5*size(),z-1.5*size(),x+.5*size(),y+1.5*size(),z+2.5*size());\n }\n protected void entityInit(){super.entityInit();dataWatcher.addObject(17,(byte)0);dataWatcher.addObject(18,(byte)0); dataWatcher.addObject(19,(byte)1);}\n public int blades(){return 4+(dataWatcher!=null?dataWatcher.getWatchableObjectByte(17):0);}\n public byte texture(){return dataWatcher!=null?dataWatcher.getWatchableObjectByte(18):0;}\n public void adjustBlades(boolean smaller){if(smaller){if(dataWatcher.getWatchableObjectByte(17)>0)dataWatcher.updateObject(17,(byte)(dataWatcher.getWatchableObjectByte(17)-1));}\n else if(dataWatcher.getWatchableObjectByte(17)<4)dataWatcher.updateObject(17,(byte)(dataWatcher.getWatchableObjectByte(17)+1));}\n public void onUpdate(){super.onUpdate();if((angle+=1)>360)angle=0;}\n \n}");
        sources.put("fixture/rotors/Wheel.java","package fixture.rotors;\npublic class Wheel extends Base {\n public Wheel(net.minecraft.world.World w){super(w);}\n public byte size(){return dataWatcher!=null?dataWatcher.getWatchableObjectByte(18):1;}\n public void adjust(boolean smaller){\n  if(smaller){if(dataWatcher.getWatchableObjectByte(18)>1)dataWatcher.updateObject(18,(byte)(dataWatcher.getWatchableObjectByte(18)-1));}\n  else {if(dataWatcher.getWatchableObjectByte(18)<2)dataWatcher.updateObject(18,(byte)(dataWatcher.getWatchableObjectByte(18)+1));}\n }\n public void setBounds(double x,double y,double z){\n  if(heading()==0||heading()==2)boundingBox.setBounds(x-1.5*size(),y-1.5*size(),z,x+2.5*size(),y+2*size(),z+.5*size());\n  else boundingBox.setBounds(x,y-1.5*size(),z-1.5*size(),x+.5*size(),y+1.5*size(),z+2.5*size());\n }\n protected void entityInit(){super.entityInit();dataWatcher.addObject(17,(byte)0); dataWatcher.addObject(18,(byte)1);}\n public void onUpdate(){super.onUpdate();if(inWater){if(dataWatcher.getWatchableObjectByte(17)==0)angle=angle<360?++angle:0;else angle=0<angle?--angle:360;}}\n}");
        sources.put("fixture/rotors/RotorModel.java","package fixture.rotors;\npublic class RotorModel extends net.minecraft.client.model.ModelBase {public net.minecraft.client.model.ModelRenderer part0,part1,part2,part3;private int count;private final Object[] angles;public RotorModel(){part0=new net.minecraft.client.model.ModelRenderer(this,0,0);part0.addBox(-3F,-3F,-2F,6,6,4);\npart1=new net.minecraft.client.model.ModelRenderer(this,55,0);part1.addBox(-1F,3F,-1F,2,30,2);\npart2=new net.minecraft.client.model.ModelRenderer(this,24,0);part2.addBox(1F,3F,-1F,10,30,1);\npart3=new net.minecraft.client.model.ModelRenderer(this,0,12);part3.addBox(-2F,-2F,0F,4,4,8);part2.rotateAngleY=(float)(Math.PI*-12)/180;\n        angles=new Object[5];for(int i=4;i<=8;i++){float[] row=new float[i];for(int j=0;j<i;j++)row[j]=(float)(Math.PI*360/i*j)/180;angles[i-4]=row;}}public void setCount(int n){count=n;}public void render(net.minecraft.entity.Entity e,float a,float b,float c,float d,float f,float s){part0.render(s);for(int i=0;i<count;i++){part1.rotateAngleZ=part2.rotateAngleZ=((float[])angles[count-4])[i];part1.render(s);part2.render(s);}part3.render(s);}}");
        sources.put("fixture/rotors/RotorRenderer.java","package fixture.rotors;\npublic class RotorRenderer extends net.minecraft.client.renderer.entity.Render {\n private final RotorModel model; private static net.minecraft.util.ResourceLocation[] textures;\n public RotorRenderer(){model=new RotorModel();textures=new net.minecraft.util.ResourceLocation[]{new net.minecraft.util.ResourceLocation(\"fixture:textures/rotor.png\"),new net.minecraft.util.ResourceLocation(\"fixture:textures/cloth.png\")};}\n public void draw(Rotor e,double x,double y,double z,float yaw,float partial){\n  org.lwjgl.opengl.GL11.glPushMatrix();bindEntityTexture(e);byte dir=e.heading();\n  if(dir==0||dir==2){if(dir==0)org.lwjgl.opengl.GL11.glTranslatef((float)x,(float)y,(float)z-(e.size()-1)/2F);\n   else org.lwjgl.opengl.GL11.glTranslatef((float)x,(float)y,(float)z+(e.size()-1)/2F);}\n  else {if(dir==3)org.lwjgl.opengl.GL11.glTranslatef((float)x-(e.size()-1)/2F,(float)y,(float)z);\n   else org.lwjgl.opengl.GL11.glTranslatef((float)x+(e.size()-1)/2F,(float)y,(float)z);}\n  org.lwjgl.opengl.GL11.glScalef(e.size(),e.size(),e.size());dir+=dir==1||dir==3?2:0; org.lwjgl.opengl.GL11.glRotatef(dir * 90,0,1,0); org.lwjgl.opengl.GL11.glRotatef(e.rotation(),0,0,1);model.setCount(e.blades());\n  model.render(e,0F,0F,0F,0F,0F,.0625F);org.lwjgl.opengl.GL11.glPopMatrix();\n }\n public net.minecraft.util.ResourceLocation getEntityTexture(net.minecraft.entity.Entity e){return textures[((Rotor)e).texture()];}\n}");
        sources.put("fixture/rotors/WheelModel.java","package fixture.rotors;\npublic class WheelModel extends net.minecraft.client.model.ModelBase {public net.minecraft.client.model.ModelRenderer part0,part1,part2,part3,part4,part5;private final float[] angles=new float[12],offsets=new float[12];public WheelModel(){part0=new net.minecraft.client.model.ModelRenderer(this,0,0);part0.addBox(-8F,-3F,-3F,14,6,6);\npart1=new net.minecraft.client.model.ModelRenderer(this,58,0);part1.addBox(4F,2F,-1F,1,30,2);\npart2=new net.minecraft.client.model.ModelRenderer(this,58,0);part2.addBox(-4F,2F,-1F,1,30,2);\npart3=new net.minecraft.client.model.ModelRenderer(this,45,10);part3.addBox(-2F,21F,-1F,5,10,1);\npart4=new net.minecraft.client.model.ModelRenderer(this,26,7);part4.addBox(3F,20F,-5F,1,10,15);\npart5=new net.minecraft.client.model.ModelRenderer(this,26,7);part5.addBox(-3F,20F,-5F,1,10,15);part4.rotateAngleX=(float)(Math.PI*20)/180;part5.rotateAngleX=(float)(Math.PI*20)/180;\n        for(int i=0;i<12;i++){angles[i]=(float)(Math.PI*i*30)/180;offsets[i]=(float)(Math.PI*(i*30-20))/180;}}public void render(net.minecraft.entity.Entity e,float a,float b,float c,float d,float f,float s){part0.render(s);for(int i=0;i<12;i++){part1.rotateAngleX=angles[i];part2.rotateAngleX=angles[i];part3.rotateAngleX=angles[i];part4.rotateAngleX=offsets[i];part5.rotateAngleX=offsets[i];part1.render(s);part2.render(s);part3.render(s);part4.render(s);part5.render(s);}}}");
        sources.put("fixture/rotors/WheelRenderer.java","package fixture.rotors;\npublic class WheelRenderer extends net.minecraft.client.renderer.entity.Render {\n private final WheelModel model; private static final net.minecraft.util.ResourceLocation texture=new net.minecraft.util.ResourceLocation(\"fixture:textures/wheel.png\");\n public WheelRenderer(){model=new WheelModel();}\n public void draw(Wheel e,double x,double y,double z,float yaw,float partial){\n  org.lwjgl.opengl.GL11.glPushMatrix();bindEntityTexture(e);byte dir=e.heading();\n  if(dir==0||dir==2){if(dir==0)org.lwjgl.opengl.GL11.glTranslatef((float)x,(float)y,(float)z-(e.size()-1)/2F);\n   else org.lwjgl.opengl.GL11.glTranslatef((float)x,(float)y,(float)z+(e.size()-1)/2F);}\n  else {if(dir==3)org.lwjgl.opengl.GL11.glTranslatef((float)x-(e.size()-1)/2F,(float)y,(float)z);\n   else org.lwjgl.opengl.GL11.glTranslatef((float)x+(e.size()-1)/2F,(float)y,(float)z);}\n  org.lwjgl.opengl.GL11.glScalef(1+(e.size()/2),1+(e.size()/2),1+(e.size()/2));dir+=dir==1||dir==3?-1:1; org.lwjgl.opengl.GL11.glRotatef(dir * 90,0,1,0); org.lwjgl.opengl.GL11.glRotatef(e.rotation(),1,0,0);\n  model.render(e,0F,0F,0F,0F,0F,.0625F);org.lwjgl.opengl.GL11.glPopMatrix();\n }\n public net.minecraft.util.ResourceLocation getEntityTexture(net.minecraft.entity.Entity e){return texture;}\n}");
        sources.put("fixture/rotors/Tray.java","package fixture.rotors;\npublic class Tray extends net.minecraft.entity.Entity {\n public static final net.minecraft.item.ItemStack EMPTY=new net.minecraft.item.ItemStack(new net.minecraft.item.Item(),0,0);\n public Tray(net.minecraft.world.World w){super(w);setSize(1F,.25F);}\n public net.minecraft.item.ItemStack item(int slot){if(slot<5){net.minecraft.item.ItemStack value=dataWatcher.getWatchableObjectItemStack(17+slot);return value!=null?value:EMPTY;}return EMPTY;}\n protected void entityInit(){for(int i=0;i<5;i++)dataWatcher.addObject(17+i,EMPTY);}\n public net.minecraft.util.AxisAlignedBB getBoundingBox(){return boundingBox;}\n public boolean canBeCollidedWith(){return !isDead;}\n public boolean attackEntityFrom(net.minecraft.util.DamageSource s,float amount){if(s.getDamageType()==\"player\")setDead();return false;}\n}");
        sources.put("fixture/rotors/TrayModel.java","package fixture.rotors;\npublic class TrayModel extends net.minecraft.client.model.ModelBase {public net.minecraft.client.model.ModelRenderer part0,part1,part2,part3,part4,part5,part6,part7,part8;public TrayModel(){textureWidth=64;textureHeight=32;part0=new net.minecraft.client.model.ModelRenderer(this,0,17);part0.addBox(-7F,1F,-6F,14,1,14);part0.setRotationPoint(0F,0F,0F);part0.setTextureSize(64,32);part0.mirror=true;turn(part0,0F,0F,0F);part1=new net.minecraft.client.model.ModelRenderer(this,0,0);part1.addBox(-8F,0F,8F,16,2,1);part1.setRotationPoint(0F,0F,0F);part1.setTextureSize(64,32);part1.mirror=true;turn(part1,0F,0F,0F);part2=new net.minecraft.client.model.ModelRenderer(this,0,0);part2.addBox(-8F,0F,-7F,16,2,1);part2.setRotationPoint(0F,0F,0F);part2.setTextureSize(64,32);part2.mirror=true;turn(part2,0F,0F,0F);part3=new net.minecraft.client.model.ModelRenderer(this,34,0);part3.addBox(7F,0F,-6F,1,2,14);part3.setRotationPoint(0F,0F,0F);part3.setTextureSize(64,32);part3.mirror=true;turn(part3,0F,0F,0F);part4=new net.minecraft.client.model.ModelRenderer(this,34,0);part4.addBox(-8F,0F,-6F,1,2,14);part4.setRotationPoint(0F,0F,0F);part4.setTextureSize(64,32);part4.mirror=true;turn(part4,0F,0F,0F);part5=new net.minecraft.client.model.ModelRenderer(this,0,4);part5.addBox(5F,2F,6F,3,1,3);part5.setRotationPoint(0F,0F,0F);part5.setTextureSize(64,32);part5.mirror=true;turn(part5,0F,0F,0F);part6=new net.minecraft.client.model.ModelRenderer(this,0,4);part6.addBox(-8F,2F,6F,3,1,3);part6.setRotationPoint(0F,0F,0F);part6.setTextureSize(64,32);part6.mirror=true;turn(part6,0F,0F,0F);part7=new net.minecraft.client.model.ModelRenderer(this,0,4);part7.addBox(5F,2F,-7F,3,1,3);part7.setRotationPoint(0F,0F,0F);part7.setTextureSize(64,32);part7.mirror=true;turn(part7,0F,0F,0F);part8=new net.minecraft.client.model.ModelRenderer(this,0,4);part8.addBox(-8F,2F,-7F,3,1,3);part8.setRotationPoint(0F,0F,0F);part8.setTextureSize(64,32);part8.mirror=true;turn(part8,0F,0F,0F);}private void turn(net.minecraft.client.model.ModelRenderer p,float x,float y,float z){p.rotateAngleX=x;p.rotateAngleY=y;p.rotateAngleZ=z;}public void render(net.minecraft.entity.Entity e,float a,float b,float c,float d,float f,float s){part0.render(s);part1.render(s);part2.render(s);part3.render(s);part4.render(s);part5.render(s);part6.render(s);part7.render(s);part8.render(s);}}");
        sources.put("fixture/rotors/TrayRenderer.java","package fixture.rotors;\npublic class TrayRenderer extends net.minecraft.client.renderer.entity.Render {\n private final TrayModel model;private static final net.minecraft.util.ResourceLocation texture=new net.minecraft.util.ResourceLocation(\"fixture:textures/tray.png\");\n public TrayRenderer(){model=new TrayModel();}\n public void draw(Tray e,double x,double y,double z,float yaw,float partial){org.lwjgl.opengl.GL11.glPushMatrix();bindEntityTexture(e);org.lwjgl.opengl.GL11.glTranslatef((float)x,(float)y+.2F,(float)z);org.lwjgl.opengl.GL11.glRotatef(180F,1F,0F,0F);model.render(e,0F,0F,0F,0F,0F,.0625F);org.lwjgl.opengl.GL11.glScalef(.7F,.7F,.7F);for(int i=0;i<5;i++)e.item(i);org.lwjgl.opengl.GL11.glPopMatrix();}\n public net.minecraft.util.ResourceLocation getEntityTexture(net.minecraft.entity.Entity e){return texture;}\n}");
        sources.put("fixture/rotors/Bootstrap.java","package fixture.rotors;\npublic class Bootstrap {static {\n cpw.mods.fml.common.registry.EntityRegistry.registerModEntity(Rotor.class,\"Rotor\",8,null,80,10,false);\n cpw.mods.fml.common.registry.EntityRegistry.registerModEntity(Wheel.class,\"Wheel\",9,null,80,10,false);\n cpw.mods.fml.common.registry.EntityRegistry.registerModEntity(Tray.class,\"Tray\",12,null,80,1,true);\n cpw.mods.fml.client.registry.RenderingRegistry.registerEntityRenderingHandler(Rotor.class,new RotorRenderer());\n cpw.mods.fml.client.registry.RenderingRegistry.registerEntityRenderingHandler(Wheel.class,new WheelRenderer());\n cpw.mods.fml.client.registry.RenderingRegistry.registerEntityRenderingHandler(Tray.class,new TrayRenderer());\n}}");
        Path input=root.resolve("sources"),output=root.resolve("classes");Files.createDirectories(output);
        List<String> args=new ArrayList<>(List.of("--release","8","-g:none","-d",output.toString()));
        for(var e:sources.entrySet()){
            Path file=input.resolve(e.getKey());Files.createDirectories(file.getParent());
            String source=floatYaw?e.getValue().replace("dir * 90,","dir * 90F,"):e.getValue();
            Files.writeString(file,source,StandardCharsets.UTF_8);args.add(file.toString());
        }
        int result=ToolProvider.getSystemJavaCompiler().run(null,null,null,args.toArray(String[]::new));
        if(result!=0)throw new IllegalStateException("Source-shape fixture compilation failed: "+result);
        Path jar=root.resolve("source-shapes.jar");
        try(JarOutputStream out=new JarOutputStream(Files.newOutputStream(jar));var files=Files.walk(output.resolve("fixture"))){
            for(Path file:files.filter(Files::isRegularFile).sorted().toList()){
                out.putNextEntry(new JarEntry(output.relativize(file).toString().replace('\\','/')));Files.copy(file,out);out.closeEntry();
            }
            if(withTextures)for(String texture:List.of("rotor","cloth","wheel","tray")){
                out.putNextEntry(new JarEntry("assets/fixture/textures/"+texture+".png"));out.write(new byte[]{1,2,3});out.closeEntry();
            }
        }
        return jar;
    }
}
