package dev.yinghuang.legacyforgebridge.convert;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import java.util.jar.JarOutputStream;

public final class VariantSnowballTeleportWrapperFixture {
    private VariantSnowballTeleportWrapperFixture(){ }
    public static Path write(Path jar)throws Exception{return rewrite(jar,32D);}
    public static Path writeWrongHorizontalSpan(Path jar)throws Exception{return rewrite(jar,16D);}

    private static Path rewrite(Path jar,double horizontalSpan)throws Exception{
        Path base=jar.resolveSibling(jar.getFileName()+".base");VariantSnowballSelectorEffectFixture.write(base);
        try(JarFile input=new JarFile(base.toFile());JarOutputStream output=new JarOutputStream(Files.newOutputStream(jar))){
            var entries=input.entries();while(entries.hasMoreElements()){
                JarEntry entry=entries.nextElement();if("foreign/entity/VariantProjectile.class".equals(entry.getName()))continue;
                output.putNextEntry(new JarEntry(entry.getName()));try(var stream=input.getInputStream(entry)){output.write(stream.readAllBytes());}output.closeEntry();
            }
            output.putNextEntry(new JarEntry("foreign/entity/VariantProjectile.class"));output.write(projectile(horizontalSpan));output.closeEntry();
        }finally{Files.deleteIfExists(base);}return jar;
    }

    private static byte[] projectile(double horizontalSpan){
        String owner="foreign/entity/VariantProjectile",selector="foreign/entity/VariantKind",tableOwner="foreign/entity/VariantProjectile$1",tableField="$SwitchMap$foreign$entity$VariantKind";
        ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V1_7,Opcodes.ACC_PUBLIC,owner,null,"net/minecraft/entity/projectile/EntitySnowball",null);w.visitField(Opcodes.ACC_PRIVATE,"kind","L"+selector+";",null,null).visitEnd();
        MethodVisitor c=w.visitMethod(Opcodes.ACC_PUBLIC,"<init>","(Lnet/minecraft/world/World;Lnet/minecraft/entity/EntityLivingBase;L"+selector+";)V",null,null);c.visitCode();c.visitVarInsn(Opcodes.ALOAD,0);c.visitVarInsn(Opcodes.ALOAD,1);c.visitVarInsn(Opcodes.ALOAD,2);c.visitMethodInsn(Opcodes.INVOKESPECIAL,"net/minecraft/entity/projectile/EntitySnowball","<init>","(Lnet/minecraft/world/World;Lnet/minecraft/entity/EntityLivingBase;)V",false);c.visitVarInsn(Opcodes.ALOAD,0);c.visitVarInsn(Opcodes.ALOAD,3);c.visitFieldInsn(Opcodes.PUTFIELD,owner,"kind","L"+selector+";");c.visitInsn(Opcodes.RETURN);c.visitMaxs(0,0);c.visitEnd();

        MethodVisitor impact=w.visitMethod(Opcodes.ACC_PROTECTED,"func_70184_a","(Lnet/minecraft/util/MovingObjectPosition;)V",null,null);impact.visitCode();
        Label selectorOk=new Label();impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,owner,"kind","L"+selector+";");impact.visitJumpInsn(Opcodes.IFNONNULL,selectorOk);impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,owner,"func_70076_C","()V",false);impact.visitInsn(Opcodes.RETURN);impact.visitLabel(selectorOk);
        Label afterHit=new Label();impact.visitVarInsn(Opcodes.ALOAD,1);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/util/MovingObjectPosition","field_72308_g","Lnet/minecraft/entity/Entity;");impact.visitJumpInsn(Opcodes.IFNULL,afterHit);impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,owner,"kind","L"+selector+";");impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,selector,"power","()B",false);impact.visitVarInsn(Opcodes.ISTORE,2);impact.visitVarInsn(Opcodes.ALOAD,1);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/util/MovingObjectPosition","field_72308_g","Lnet/minecraft/entity/Entity;");impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,owner,"func_85052_h","()Lnet/minecraft/entity/EntityLivingBase;",false);impact.visitMethodInsn(Opcodes.INVOKESTATIC,"net/minecraft/util/DamageSource","func_76356_a","(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;",false);impact.visitVarInsn(Opcodes.ILOAD,2);impact.visitInsn(Opcodes.I2F);impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/entity/Entity","func_70097_a","(Lnet/minecraft/util/DamageSource;F)Z",false);impact.visitInsn(Opcodes.POP);
        Label afterSpecial=new Label(),custom=new Label();impact.visitVarInsn(Opcodes.ALOAD,1);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/util/MovingObjectPosition","field_72308_g","Lnet/minecraft/entity/Entity;");impact.visitTypeInsn(Opcodes.INSTANCEOF,"net/minecraft/entity/EntityLiving");impact.visitJumpInsn(Opcodes.IFEQ,afterSpecial);impact.visitVarInsn(Opcodes.ALOAD,1);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/util/MovingObjectPosition","field_72308_g","Lnet/minecraft/entity/Entity;");impact.visitTypeInsn(Opcodes.CHECKCAST,"net/minecraft/entity/EntityLiving");impact.visitVarInsn(Opcodes.ASTORE,4);impact.visitFieldInsn(Opcodes.GETSTATIC,tableOwner,tableField,"[I");impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,owner,"kind","L"+selector+";");impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,selector,"ordinal","()I",false);impact.visitInsn(Opcodes.IALOAD);impact.visitLookupSwitchInsn(afterSpecial,new int[]{1},new Label[]{custom});impact.visitLabel(custom);impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitVarInsn(Opcodes.ALOAD,4);impact.visitMethodInsn(Opcodes.INVOKESPECIAL,owner,"teleportRandomly","(Lnet/minecraft/entity/EntityLiving;)Z",false);impact.visitInsn(Opcodes.POP);impact.visitJumpInsn(Opcodes.GOTO,afterSpecial);impact.visitLabel(afterSpecial);impact.visitLabel(afterHit);
        impact.visitInsn(Opcodes.ICONST_0);impact.visitVarInsn(Opcodes.ISTORE,3);Label loop=new Label(),afterLoop=new Label();impact.visitLabel(loop);impact.visitVarInsn(Opcodes.ILOAD,3);impact.visitIntInsn(Opcodes.BIPUSH,8);impact.visitJumpInsn(Opcodes.IF_ICMPGE,afterLoop);impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70170_p","Lnet/minecraft/world/World;");impact.visitLdcInsn("snowballpoof");impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70165_t","D");impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70163_u","D");impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70161_v","D");impact.visitInsn(Opcodes.DCONST_0);impact.visitInsn(Opcodes.DCONST_0);impact.visitInsn(Opcodes.DCONST_0);impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"net/minecraft/world/World","func_72869_a","(Ljava/lang/String;DDDDDD)V",false);impact.visitIincInsn(3,1);impact.visitJumpInsn(Opcodes.GOTO,loop);impact.visitLabel(afterLoop);Label done=new Label();impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70170_p","Lnet/minecraft/world/World;");impact.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/world/World","field_72995_K","Z");impact.visitJumpInsn(Opcodes.IFNE,done);impact.visitVarInsn(Opcodes.ALOAD,0);impact.visitMethodInsn(Opcodes.INVOKEVIRTUAL,owner,"func_70106_y","()V",false);impact.visitLabel(done);impact.visitInsn(Opcodes.RETURN);impact.visitMaxs(0,0);impact.visitEnd();

        MethodVisitor random=w.visitMethod(Opcodes.ACC_PRIVATE,"teleportRandomly","(Lnet/minecraft/entity/EntityLiving;)Z",null,null);random.visitCode();
        random.visitVarInsn(Opcodes.ALOAD,0);random.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70165_t","D");random.visitVarInsn(Opcodes.ALOAD,0);random.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70146_Z","Ljava/util/Random;");random.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"java/util/Random","nextDouble","()D",false);random.visitLdcInsn(0.5D);random.visitInsn(Opcodes.DSUB);random.visitLdcInsn(horizontalSpan);random.visitInsn(Opcodes.DMUL);random.visitInsn(Opcodes.DADD);random.visitVarInsn(Opcodes.DSTORE,2);
        random.visitVarInsn(Opcodes.ALOAD,0);random.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70163_u","D");random.visitVarInsn(Opcodes.ALOAD,0);random.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70146_Z","Ljava/util/Random;");random.visitIntInsn(Opcodes.BIPUSH,8);random.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"java/util/Random","nextInt","(I)I",false);random.visitInsn(Opcodes.ICONST_4);random.visitInsn(Opcodes.ISUB);random.visitInsn(Opcodes.I2D);random.visitInsn(Opcodes.DADD);random.visitVarInsn(Opcodes.DSTORE,4);
        random.visitVarInsn(Opcodes.ALOAD,0);random.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70161_v","D");random.visitVarInsn(Opcodes.ALOAD,0);random.visitFieldInsn(Opcodes.GETFIELD,"net/minecraft/entity/Entity","field_70146_Z","Ljava/util/Random;");random.visitMethodInsn(Opcodes.INVOKEVIRTUAL,"java/util/Random","nextDouble","()D",false);random.visitLdcInsn(0.5D);random.visitInsn(Opcodes.DSUB);random.visitLdcInsn(horizontalSpan);random.visitInsn(Opcodes.DMUL);random.visitInsn(Opcodes.DADD);random.visitVarInsn(Opcodes.DSTORE,6);
        random.visitVarInsn(Opcodes.ALOAD,0);random.visitVarInsn(Opcodes.ALOAD,1);random.visitVarInsn(Opcodes.DLOAD,2);random.visitVarInsn(Opcodes.DLOAD,4);random.visitVarInsn(Opcodes.DLOAD,6);random.visitMethodInsn(Opcodes.INVOKESPECIAL,owner,"teleportTo","(Lnet/minecraft/entity/EntityLiving;DDD)Z",false);random.visitInsn(Opcodes.IRETURN);random.visitMaxs(0,0);random.visitEnd();

        MethodVisitor to=w.visitMethod(Opcodes.ACC_PRIVATE,"teleportTo","(Lnet/minecraft/entity/EntityLiving;DDD)Z",null,null);to.visitCode();to.visitInsn(Opcodes.ICONST_1);to.visitInsn(Opcodes.IRETURN);to.visitMaxs(0,0);to.visitEnd();w.visitEnd();return w.toByteArray();
    }
}
